


cloud:
  aws:
    region:
      auto: false
      static: sa-east-1
      use-default-aws-region-chain: true
    stack: false
    stack.auto: false
    credentials:
      access-key: AKIAQF4IYCN6IXCMCA4C
      secret-key: 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
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error